/**
 * Deal-constraint alignment test.
 *
 * Validates that every hand generated by a bundle's deal constraints
 * satisfies at least one of the bundle's R1 surface clauses. This catches
 * drift between the authored deal constraints (used for practice deal
 * generation) and the convention's actual eligibility logic.
 *
 * Example bug this prevents: deal constraints allowing 5-card majors
 * for Stayman practice, while the Stayman surface requires no 5-card major.
 */
import { describe, it, expect } from "vitest";
import { generateDeal } from "../../../engine/deal-generator";
import { evaluateHand } from "../../../engine/hand-evaluator";
import { evaluateFacts } from "../../pipeline/fact-evaluator";
import { evaluateBidMeaning } from "../../pipeline/meaning-evaluator";
import { createSharedFactCatalog } from "../../pipeline/shared-fact-catalog";
import { createSystemFactCatalog } from "../../pipeline/system-fact-catalog";
import { createFactCatalog } from "../../core/fact-catalog";
import type { FactCatalog } from "../../core/fact-catalog";
import type { BidMeaning } from "../../pipeline/meaning";
import type { ConventionBundle } from "../../core/bundle/bundle-types";
import { getBundleInput, resolveBundle } from "../system-registry";
import { SAYC_SYSTEM_CONFIG } from "../system-config";
import { Seat } from "../../../engine/types";
import type { Hand } from "../../../engine/types";

const TRIALS = 30;
const sys = SAYC_SYSTEM_CONFIG;

// ── Helpers ──────────────────────────────────────────────────────

/** Build a fact catalog that includes shared, system, and all module facts. */
function buildCatalog(bundle: ConventionBundle): FactCatalog {
  return createFactCatalog(
    createSharedFactCatalog(),
    createSystemFactCatalog(sys),
    ...bundle.modules.map((m) => m.facts),
  );
}

/**
 * Collect the user-facing R1 surfaces from a bundle.
 *
 * Each bundle has a different structure:
 * - NT bundles: responder surfaces in "idle" phase of stayman/transfer modules
 * - Bergen: responder surfaces in "opened-hearts"/"opened-spades" phases
 * - DONT: overcaller surfaces in "r1" phase
 * - Weak Twos: opener surfaces in "idle" phase (opener is North, not user)
 */
function collectR1Surfaces(
  bundle: ConventionBundle,
  phases: readonly string[],
): BidMeaning[] {
  return bundle.modules.flatMap((m) =>
    (m.states ?? [])
      .filter((e) => {
        const p = e.phase;
        return Array.isArray(p)
          ? p.some((ph) => phases.includes(ph))
          : phases.includes(p as string);
      })
      .flatMap((e) => e.surfaces),
  );
}

/**
 * Check whether a hand satisfies at least one R1 surface.
 * Returns the first satisfied surface's meaningId, or a diagnostic object.
 */
function checkHandAgainstSurfaces(
  hand: Hand,
  surfaces: readonly BidMeaning[],
  catalog: FactCatalog,
): { satisfied: true; meaningId: string } | { satisfied: false; diagnostics: string } {
  const ev = evaluateHand(hand);
  const facts = evaluateFacts(hand, ev, catalog);

  for (const surface of surfaces) {
    const proposal = evaluateBidMeaning(surface, facts);
    if (proposal.clauses.every((c) => c.satisfied)) {
      return { satisfied: true, meaningId: surface.meaningId };
    }
  }

  // Build diagnostic: show which clauses failed on each surface
  const lines: string[] = [];
  for (const surface of surfaces) {
    const proposal = evaluateBidMeaning(surface, facts);
    const failed = proposal.clauses
      .filter((c) => !c.satisfied)
      .map((c) => `${c.factId} ${c.operator} ${JSON.stringify(c.value)} (got ${c.observedValue ?? "missing"})`)
      .join(", ");
    lines.push(`  ${surface.meaningId}: [${failed}]`);
  }
  return { satisfied: false, diagnostics: lines.join("\n") };
}

// ── Tests ────────────────────────────────────────────────────────

describe("deal constraint alignment", () => {
  describe("nt-stayman", () => {
    const bundle = resolveBundle(getBundleInput("nt-stayman")!, sys);
    const constraints = bundle.dealConstraints;
    const catalog = buildCatalog(bundle);
    // Stayman R1: responder surfaces in "idle" phase
    const r1 = collectR1Surfaces(bundle, ["idle"]).filter(
      (s) => s.meaningId.startsWith("stayman:"),
    );

    it("has R1 surfaces to test against", () => {
      expect(r1.length).toBeGreaterThan(0);
    });

    it(`every generated South hand satisfies the Stayman R1 surface (${TRIALS} trials)`, () => {
      for (let i = 0; i < TRIALS; i++) {
        const { deal } = generateDeal(constraints);
        const result = checkHandAgainstSurfaces(deal.hands[Seat.South], r1, catalog);
        if (!result.satisfied) {
          expect.fail(
            `Deal ${i + 1}: South hand satisfies no Stayman R1 surface.\n${result.diagnostics}`,
          );
        }
      }
    });
  });

  describe("nt-transfers", () => {
    const bundle = resolveBundle(getBundleInput("nt-transfers")!, sys);
    const constraints = bundle.dealConstraints;
    const catalog = buildCatalog(bundle);
    // Transfer R1: responder surfaces in "idle" phase
    const r1 = collectR1Surfaces(bundle, ["idle"]).filter(
      (s) => s.meaningId.startsWith("transfer:"),
    );

    it("has R1 surfaces to test against", () => {
      expect(r1.length).toBeGreaterThan(0);
    });

    it(`every generated South hand satisfies a transfer R1 surface (${TRIALS} trials)`, () => {
      for (let i = 0; i < TRIALS; i++) {
        const { deal } = generateDeal(constraints);
        const result = checkHandAgainstSurfaces(deal.hands[Seat.South], r1, catalog);
        if (!result.satisfied) {
          expect.fail(
            `Deal ${i + 1}: South hand satisfies no transfer R1 surface.\n${result.diagnostics}`,
          );
        }
      }
    });
  });

  describe("bergen-bundle", () => {
    const bundle = resolveBundle(getBundleInput("bergen-bundle")!, sys);
    const constraints = bundle.dealConstraints;
    const catalog = buildCatalog(bundle);
    // Bergen R1: responder surfaces in "opened-hearts" / "opened-spades"
    const r1 = collectR1Surfaces(bundle, ["opened-hearts", "opened-spades"]);

    it("has R1 surfaces to test against", () => {
      expect(r1.length).toBeGreaterThan(0);
    });

    it(`every generated South hand satisfies a Bergen R1 surface (${TRIALS} trials)`, () => {
      for (let i = 0; i < TRIALS; i++) {
        const { deal } = generateDeal(constraints);
        const result = checkHandAgainstSurfaces(deal.hands[Seat.South], r1, catalog);
        if (!result.satisfied) {
          expect.fail(
            `Deal ${i + 1}: South hand satisfies no Bergen R1 surface.\n${result.diagnostics}`,
          );
        }
      }
    });
  });

  describe("dont-bundle", () => {
    const bundle = resolveBundle(getBundleInput("dont-bundle")!, sys);
    const constraints = bundle.dealConstraints;
    const catalog = buildCatalog(bundle);
    // DONT R1: overcaller surfaces in "r1" phase
    const r1 = collectR1Surfaces(bundle, ["r1"]);

    it("has R1 surfaces to test against", () => {
      expect(r1.length).toBeGreaterThan(0);
    });

    it(`every generated South hand satisfies a DONT R1 surface (${TRIALS} trials)`, () => {
      for (let i = 0; i < TRIALS; i++) {
        const { deal } = generateDeal(constraints);
        const result = checkHandAgainstSurfaces(deal.hands[Seat.South], r1, catalog);
        if (!result.satisfied) {
          expect.fail(
            `Deal ${i + 1}: South hand satisfies no DONT R1 surface.\n${result.diagnostics}`,
          );
        }
      }
    });
  });
});
